//! Entitlement / license verification — offline Ed25519 JWT.
//!
//! The BitVanes **engine** is local-first and zero-trust: it never makes
//! network calls. License verification is therefore fully offline: a license
//! key is a signed JWT (`BV-{TIER}-{header.payload.signature}`) whose
//! Ed25519 signature is checked against an embedded public key. No call home,
//! no revocation server (expiry is baked into the signed payload).
//!
//! The matching **private key** lives only on the minting backend
//! (`web/api/services/licenseSigner.js`); see `examples/keygen.rs` to rotate.
//!
//! # Freemium model
//!
//! - **Free** (no key): text & stream scrubbing, the core PII ruleset, the
//!   local daemon + dashboard. Activated simply by running the software.
//! - **Pro** (`BV-SOLO-…`): PDF destructive redaction, office formats, the
//!   personal-name gazetteer, batch/directory processing, the hash policy.
//! - **Enterprise** (`BV-BUSINESS-…`): everything in Pro, multi-seat.
//!
//! Pro features call [`require_pro`] before running; free features never
//! check entitlement.

// Several plan tiers / fields are part of the documented contract and are
// exercised by tests but not always by the daemon happy path.
#![allow(dead_code)]

use std::path::PathBuf;
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use base64::Engine;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::Deserialize;

/// Embedded Ed25519 verification key (production). Generated by
/// `cargo run --example keygen` (OsRng — no committed seed, so the matching
/// private key is not recoverable from the repo). Keep the private key only
/// in the minting backend (`BITVANES_LICENSE_PRIVATE_KEY` Vercel env var).
pub const LICENSE_PUBKEY: [u8; 32] = [
    0xfc, 0xab, 0x1e, 0x5f, 0x21, 0x0f, 0x81, 0x7b, 0x1f, 0x38, 0x01, 0xb6, 0x35, 0xff, 0x65, 0x29,
    0x52, 0x2a, 0x19, 0x2c, 0x93, 0x8f, 0x74, 0xb3, 0x95, 0x01, 0x06, 0x09, 0xa9, 0xa2, 0xde, 0xd6,
];

/// Expected license-key prefix.
pub const LICENSE_KEY_PREFIX: &str = "BV-";

// ===========================================================================
// Plan + status
// ===========================================================================

/// Service tier mirrored from the signed license payload.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Plan {
    /// No key — the free / open-source floor.
    #[default]
    OpenSource,
    /// `BV-SOLO-…` (1 seat).
    Pro,
    /// `BV-BUSINESS-…` (5 seats).
    Enterprise,
}

impl Plan {
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::OpenSource => "open-source",
            Self::Pro => "solo",
            Self::Enterprise => "business",
        }
    }

    /// Seats implied by the plan (for display).
    #[must_use]
    pub fn seats(self) -> u32 {
        match self {
            Self::OpenSource => 0,
            Self::Pro => 1,
            Self::Enterprise => 5,
        }
    }
}

/// The resolved entitlement for the running process.
#[derive(Debug, Clone)]
pub enum EntitlementStatus {
    /// No license key present — the open-source floor.
    OpenSource,
    /// A license key was supplied and verified.
    Licensed { plan: Plan, sub: String, exp: i64 },
    /// A key was supplied but is malformed, expired, or has a bad signature.
    Invalid { reason: String },
}

impl EntitlementStatus {
    /// Effective plan under this status.
    #[must_use]
    pub fn plan(&self) -> Plan {
        match self {
            Self::Licensed { plan, .. } => *plan,
            _ => Plan::OpenSource,
        }
    }

    /// `true` if paid (Pro/Enterprise) features may be served.
    #[must_use]
    pub fn is_pro_or_above(&self) -> bool {
        matches!(self.plan(), Plan::Pro | Plan::Enterprise)
    }

    /// Backwards-compatible alias for [`Self::is_pro_or_above`].
    #[must_use]
    pub fn allow_paid_features(&self) -> bool {
        self.is_pro_or_above()
    }

    /// Short human-readable label for logs / `/health`.
    #[must_use]
    pub fn label(&self) -> String {
        match self {
            Self::OpenSource => "free (no license key)".to_string(),
            Self::Licensed { plan, sub, exp } => {
                format!("{} (sub: {sub}, exp: {exp})", plan.as_str())
            }
            Self::Invalid { reason } => format!("invalid license: {reason}"),
        }
    }
}

// ===========================================================================
// Checker trait + impls
// ===========================================================================

/// The hook the daemon / CLI calls to resolve entitlement.
pub trait EntitlementChecker: Send + Sync {
    fn status(&self) -> EntitlementStatus;
}

/// Default permissive checker: no key → free tier.
#[derive(Debug, Default)]
pub struct OpenSourceChecker;

impl EntitlementChecker for OpenSourceChecker {
    fn status(&self) -> EntitlementStatus {
        EntitlementStatus::OpenSource
    }
}

/// Checker backed by a parsed license key (verified against [`    LICENSE_PUBKEY`]).
#[derive(Debug)]
pub struct LicenseChecker {
    status: EntitlementStatus,
}

impl LicenseChecker {
    /// Build a checker from a parsed key. Verification happens once, here.
    #[must_use]
    pub fn from_key(key: LicenseKey) -> Self {
        Self {
            status: key_to_status(&key, &LICENSE_PUBKEY),
        }
    }
}

impl EntitlementChecker for LicenseChecker {
    fn status(&self) -> EntitlementStatus {
        self.status.clone()
    }
}

fn key_to_status(key: &LicenseKey, pubkey: &[u8; 32]) -> EntitlementStatus {
    match key.verify(pubkey) {
        Ok(p) => {
            let plan = match p.tier.as_str() {
                "solo" => Plan::Pro,
                "business" => Plan::Enterprise,
                other => {
                    return EntitlementStatus::Invalid {
                        reason: format!("unknown tier '{other}'"),
                    };
                }
            };
            EntitlementStatus::Licensed {
                plan,
                sub: p.sub,
                exp: p.exp,
            }
        }
        Err(e) => EntitlementStatus::Invalid { reason: e },
    }
}

// ===========================================================================
// License key parsing + signature verification
// ===========================================================================

/// The signed JWT payload.
#[derive(Debug, Deserialize)]
struct LicensePayload {
    sub: String,
    tier: String,
    #[allow(dead_code)]
    iss: String,
    #[allow(dead_code)]
    iat: i64,
    exp: i64,
}

/// A `BV-{TIER}-{jwt}` license string, parsed but not yet verified.
#[derive(Debug, Clone)]
pub struct LicenseKey {
    raw: String,
    tier_prefix: String, // "SOLO" | "BUSINESS"
    jwt: String,         // header.payload.signature
}

impl LicenseKey {
    /// Parses a raw key string (`"BV-SOLO-eyJ…"`) without verifying it.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the prefix/tier is missing or the JWT is malformed.
    pub fn parse(raw: &str) -> Result<Self, String> {
        let trimmed = raw.trim();
        let rest = trimmed
            .strip_prefix(LICENSE_KEY_PREFIX)
            .ok_or("license key must start with 'BV-'")?;
        let (tier, jwt) = rest
            .split_once('-')
            .ok_or("missing tier segment (expected BV-SOLO-… or BV-BUSINESS-…)")?;
        let tier_up = tier.to_ascii_uppercase();
        if !matches!(tier_up.as_str(), "SOLO" | "BUSINESS") {
            return Err(format!("unknown tier '{tier}' (expected SOLO|BUSINESS)"));
        }
        if jwt.split('.').count() != 3 {
            return Err("license JWT must have 3 dot-separated segments".to_string());
        }
        Ok(Self {
            raw: trimmed.to_string(),
            tier_prefix: tier_up,
            jwt: jwt.to_string(),
        })
    }

    /// The raw key string (including prefix).
    #[must_use]
    pub fn raw(&self) -> &str {
        &self.raw
    }

    /// Verify the Ed25519 signature + expiry against `pubkey`. Decodes and
    /// returns the signed payload.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the signature is invalid, the payload is malformed,
    /// the key is expired, or the prefix tier does not match the signed tier.
    fn verify(&self, pubkey: &[u8; 32]) -> Result<LicensePayload, String> {
        let vk = VerifyingKey::from_bytes(pubkey).map_err(|e| format!("bad pubkey: {e}"))?;

        let mut parts = self.jwt.splitn(3, '.');
        let header_b64 = parts.next().expect("splitn yielded no first segment");
        let payload_b64 = parts.next().ok_or("missing payload segment")?;
        let sig_b64 = parts.next().ok_or("missing signature segment")?;

        // JWT signing input is "header.payload" (the literal bytes).
        let signing_input = format!("{header_b64}.{payload_b64}");
        let sig_bytes = URL_SAFE_NO_PAD
            .decode(sig_b64)
            .map_err(|e| format!("bad signature encoding: {e}"))?;
        let sig = Signature::from_slice(&sig_bytes).map_err(|e| format!("bad signature: {e}"))?;

        // Constant-time Ed25519 verification.
        vk.verify(signing_input.as_bytes(), &sig)
            .map_err(|_| "invalid signature".to_string())?;

        let payload_bytes = URL_SAFE_NO_PAD
            .decode(payload_b64)
            .map_err(|e| format!("bad payload encoding: {e}"))?;
        let payload: LicensePayload =
            serde_json::from_slice(&payload_bytes).map_err(|e| format!("bad payload JSON: {e}"))?;

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs() as i64)
            .unwrap_or(0);
        if payload.exp <= now {
            return Err("license expired".to_string());
        }
        if !payload.tier.eq_ignore_ascii_case(&self.tier_prefix) {
            return Err(format!(
                "tier mismatch: prefix '{}' but payload tier '{}'",
                self.tier_prefix, payload.tier
            ));
        }
        Ok(payload)
    }
}

// ===========================================================================
// Freemium gating
// ===========================================================================

/// Returns `Ok(())` if the status permits a Pro feature, else `Err` with a
/// user-actionable message. Free features never call this.
///
/// # Errors
///
/// `Err(message)` when the status is not Pro/Enterprise.
pub fn require_pro(status: &EntitlementStatus, feature: &str) -> Result<(), String> {
    if status.is_pro_or_above() {
        return Ok(());
    }
    Err(match status {
        EntitlementStatus::OpenSource => format!(
            "'{feature}' is a BitVanes Pro feature. Buy a key at \
             https://bitvanes.com#get-started then run `bitvanes config --key BV-…`."
        ),
        EntitlementStatus::Invalid { reason } => {
            format!("'{feature}' is a Pro feature but your license is invalid: {reason}")
        }
        EntitlementStatus::Licensed { .. } => {
            format!("'{feature}' requires a higher-tier license")
        }
    })
}

// ===========================================================================
// Key resolution + persistence
// ===========================================================================

/// Resolves the entitlement checker from, in priority order:
/// 1. an explicit `key` arg (`--license-key`),
/// 2. `BITVANES_LICENSE_KEY` env,
/// 3. the persisted key file (`$HOME/.bitvanes/license`, written by
///    `bitvanes config --key`),
/// 4. none → free / open-source.
///
/// A malformed/unverifiable key prints a warning and falls back to free (the
/// software remains usable; only Pro features are gated).
#[must_use]
pub fn resolve_checker(explicit: Option<&str>) -> Arc<dyn EntitlementChecker> {
    let raw = explicit
        .map(str::to_string)
        .or_else(|| std::env::var("BITVANES_LICENSE_KEY").ok())
        .or_else(read_persisted_key)
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());
    match raw {
        Some(r) => match LicenseKey::parse(&r) {
            Ok(k) => Arc::new(LicenseChecker::from_key(k)),
            Err(e) => {
                eprintln!("warning: license key ignored ({e}); using Free tier");
                Arc::new(OpenSourceChecker)
            }
        },
        None => Arc::new(OpenSourceChecker),
    }
}

/// Path to the persisted license key (`$HOME/.bitvanes/license`).
fn license_path() -> Option<PathBuf> {
    let home = std::env::var_os("HOME")?;
    Some(PathBuf::from(home).join(".bitvanes").join("license"))
}

/// Reads the persisted license key, if any.
fn read_persisted_key() -> Option<String> {
    let path = license_path()?;
    std::fs::read_to_string(&path)
        .ok()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty())
}

/// Persists a verified license key to `$HOME/.bitvanes/license`.
///
/// # Errors
///
/// Returns `Err` if `HOME` is unset or the file cannot be written.
pub fn save_key(key: &LicenseKey) -> Result<(), String> {
    let path = license_path().ok_or("HOME not set; cannot persist license")?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("create dir: {e}"))?;
    }
    std::fs::write(&path, key.raw()).map_err(|e| format!("write license: {e}"))
}

/// Parses, verifies, and persists a license key (`bitvanes config --key BV-…`).
/// Returns a success message on completion.
///
/// # Errors
///
/// Returns `Err` if the key is malformed, fails signature/expiry verification,
/// or cannot be persisted.
pub fn install_key(raw: &str) -> Result<String, String> {
    let key = LicenseKey::parse(raw)?;
    let payload = key.verify(&LICENSE_PUBKEY)?;
    save_key(&key)?;
    Ok(format!(
        "License verified and saved (tier: {}, sub: {}). Pro features unlocked.",
        payload.tier, payload.sub
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use ed25519_dalek::{Signer, SigningKey};
    use rand::SeedableRng;
    use rand::rngs::StdRng;
    use serde_json::json;

    fn b64u(b: &[u8]) -> String {
        URL_SAFE_NO_PAD.encode(b)
    }

    /// Mints a `BV-{TIER}-<jwt>` signed by `sk`. Mirrors `examples/keygen.rs`
    /// and the JS backend signer so the verifier is exercised end-to-end.
    fn mint(sk: &SigningKey, tier: &str, exp: i64) -> String {
        let header = b64u(br#"{"alg":"EdDSA","typ":"JWT"}"#);
        let payload = json!({
            "sub": "tester",
            "tier": tier,
            "iss": "bitvanes.com",
            "iat": 1_700_000_000_i64,
            "exp": exp,
        });
        let payload_bytes = serde_json::to_vec(&payload).unwrap();
        let payload_b64 = b64u(&payload_bytes);
        let signing_input = format!("{header}.{payload_b64}");
        let sig = sk.sign(signing_input.as_bytes());
        format!(
            "BV-{}-{}.{}",
            tier.to_uppercase(),
            signing_input,
            b64u(&sig.to_bytes())
        )
    }

    #[test]
    fn round_trip_fresh_keypair_verifies() {
        let mut rng = StdRng::seed_from_u64(42);
        let sk = SigningKey::generate(&mut rng);
        let pk = sk.verifying_key().to_bytes();
        let key = LicenseKey::parse(&mint(&sk, "solo", 1_900_000_000)).unwrap();
        let payload = key.verify(&pk).expect("freshly minted key must verify");
        assert_eq!(payload.tier, "solo");
    }

    #[test]
    fn embedded_pubkey_is_valid_ed25519_key() {
        // The embedded LICENSE_PUBKEY must be a valid 32-byte Ed25519 key
        // (i.e. VerifyingKey::from_bytes succeeds). This catches a malformed
        // embed. The full mint→verify round-trip is covered by
        // `round_trip_fresh_keypair_verifies` above (with a test-generated
        // keypair), and end-to-end against the embedded key is proven by the
        // dev-mint → CLI verify integration test.
        assert!(
            VerifyingKey::from_bytes(&LICENSE_PUBKEY).is_ok(),
            "LICENSE_PUBKEY must be a valid Ed25519 public key"
        );
    }

    #[test]
    fn tampered_signature_is_rejected() {
        let mut rng = StdRng::seed_from_u64(7);
        let sk = SigningKey::generate(&mut rng);
        let pk = sk.verifying_key().to_bytes();
        let mut raw = mint(&sk, "solo", 1_900_000_000);
        // Flip the last character of the signature.
        let last = raw.len() - 1;
        let c = raw.as_bytes()[last];
        raw.pop();
        raw.push(if c == b'A' { 'B' } else { 'A' });
        let key = LicenseKey::parse(&raw).unwrap();
        assert!(
            key.verify(&pk).is_err(),
            "tampered signature must not verify"
        );
    }

    #[test]
    fn expired_license_is_rejected() {
        let mut rng = StdRng::seed_from_u64(9);
        let sk = SigningKey::generate(&mut rng);
        let pk = sk.verifying_key().to_bytes();
        let past = 1_000; // 1970
        let key = LicenseKey::parse(&mint(&sk, "solo", past)).unwrap();
        let err = key.verify(&pk).unwrap_err();
        assert!(err.contains("expired"), "got: {err}");
    }

    #[test]
    fn tier_mismatch_between_prefix_and_payload_is_rejected() {
        // Mint a solo payload but label the prefix BUSINESS.
        let mut rng = StdRng::seed_from_u64(11);
        let sk = SigningKey::generate(&mut rng);
        let pk = sk.verifying_key().to_bytes();
        let header = b64u(br#"{"alg":"EdDSA","typ":"JWT"}"#);
        let payload = json!({ "sub":"t","tier":"solo","iss":"bitvanes.com","iat":1_700_000_000_i64,"exp":1_900_000_000_i64 });
        let payload_b64 = b64u(&serde_json::to_vec(&payload).unwrap());
        let signing_input = format!("{header}.{payload_b64}");
        let sig = sk.sign(signing_input.as_bytes());
        let raw = format!("BV-BUSINESS-{signing_input}.{}", b64u(&sig.to_bytes()));
        let key = LicenseKey::parse(&raw).unwrap();
        let err = key.verify(&pk).unwrap_err();
        assert!(err.contains("tier mismatch"), "got: {err}");
    }

    #[test]
    fn parse_rejects_bad_prefix_and_tier() {
        assert!(LicenseKey::parse("sk_live_123").is_err());
        assert!(LicenseKey::parse("BV-FREE-x.y.z").is_err());
        assert!(LicenseKey::parse("BV-SOLO-notajwt").is_err());
    }

    #[test]
    fn require_pro_allows_pro_denies_free() {
        let pro = EntitlementStatus::Licensed {
            plan: Plan::Pro,
            sub: "t".into(),
            exp: 1_900_000_000,
        };
        assert!(require_pro(&pro, "PDF redaction").is_ok());

        let free = EntitlementStatus::OpenSource;
        let err = require_pro(&free, "PDF redaction").unwrap_err();
        assert!(err.contains("Pro feature"));
        assert!(err.contains("bitvanes.com"));
    }
}
